# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u4f1a\u793e\u540d')),
                ('japanese_spell', models.CharField(max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca', blank=True)),
                ('found_date', models.DateField(null=True, verbose_name='\u8a2d\u7acb\u5e74\u6708\u65e5', blank=True)),
                ('capital', models.BigIntegerField(null=True, verbose_name='\u8cc7\u672c\u91d1', blank=True)),
                ('post_code', models.CharField(max_length=8, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7', blank=True)),
                ('address1', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11', blank=True)),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12', blank=True)),
                ('tel', models.CharField(max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('fax', models.CharField(max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9', blank=True)),
                ('president', models.CharField(max_length=30, null=True, verbose_name='\u4ee3\u8868\u8005\u540d', blank=True)),
                ('employee_count', models.IntegerField(null=True, verbose_name='\u5f93\u696d\u54e1\u6570', blank=True)),
                ('sale_amount', models.BigIntegerField(null=True, verbose_name='\u58f2\u4e0a\u9ad8', blank=True)),
                ('payment_type', models.CharField(max_length=2, null=True, verbose_name='\u652f\u6255\u65b9\u6cd5', blank=True)),
                ('payment_day', models.CharField(max_length=2, null=True, verbose_name='\u652f\u6255\u65e5', blank=True)),
                ('comment', models.TextField(null=True, verbose_name='\u5099\u8003', blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2015, 9, 12, 16, 48, 26, 611467), auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2015, 9, 12, 16, 48, 26, 611490), auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u53d6\u5f15\u5148',
                'verbose_name_plural': '\u53d6\u5f15\u5148',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClientMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u524d')),
                ('email', models.EmailField(max_length=75, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('client', models.ForeignKey(verbose_name='\u6240\u5c5e\u4f1a\u793e', to='eb.Client')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u304a\u5ba2\u69d8',
                'verbose_name_plural': '\u304a\u5ba2\u69d8',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u4f1a\u793e\u540d')),
                ('japanese_spell', models.CharField(max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca', blank=True)),
                ('found_date', models.DateField(null=True, verbose_name='\u8a2d\u7acb\u5e74\u6708\u65e5', blank=True)),
                ('capital', models.BigIntegerField(null=True, verbose_name='\u8cc7\u672c\u91d1', blank=True)),
                ('post_code', models.CharField(max_length=8, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7', blank=True)),
                ('address1', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11', blank=True)),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12', blank=True)),
                ('tel', models.CharField(max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('fax', models.CharField(max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9', blank=True)),
            ],
            options={
                'verbose_name': '\u4f1a\u793e',
                'verbose_name_plural': '\u4f1a\u793e',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('employee_id', models.CharField(unique=True, max_length=30, verbose_name='\u793e\u54e1ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u524d')),
                ('japanese_spell', models.CharField(max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca', blank=True)),
                ('english_spell', models.CharField(max_length=30, null=True, verbose_name='\u30ed\u30fc\u30de\u5b57', blank=True)),
                ('birthday', models.DateField(null=True, verbose_name='\u751f\u5e74\u6708\u65e5', blank=True)),
                ('graduate_date', models.DateField(null=True, verbose_name='\u5352\u696d\u5e74\u6708\u65e5', blank=True)),
                ('degree', models.IntegerField(blank=True, null=True, verbose_name='\u5b66\u6b74', choices=[(1, '\u5c0f\u30fb\u4e2d\u5b66\u6821'), (2, '\u9ad8\u7b49\u5b66\u6821'), (3, '\u5c02\u9580\u5b66\u6821'), (4, '\u9ad8\u7b49\u5c02\u9580\u5b66\u6821'), (5, '\u77ed\u671f\u5927\u5b66'), (6, '\u5927\u5b66\u5b66\u90e8'), (7, '\u5927\u5b66\u5927\u5b66\u9662')])),
                ('email', models.EmailField(max_length=75, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('post_code', models.CharField(max_length=8, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7', blank=True)),
                ('address1', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11', blank=True)),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12', blank=True)),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('member_type', models.IntegerField(default=0, verbose_name='\u793e\u54e1\u533a\u5206', choices=[(0, '\u6b63\u793e\u54e1'), (1, '\u5951\u7d04\u793e\u54e1'), (3, '\u6d3e\u9063\u793e\u54e1'), (4, '\u500b\u4eba\u4e8b\u696d\u6240')])),
                ('company', models.ForeignKey(verbose_name='\u4f1a\u793e', blank=True, to='eb.Company', null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u793e\u54e1',
                'verbose_name_plural': '\u793e\u54e1',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=50, verbose_name='\u6848\u4ef6\u540d\u79f0')),
                ('description', models.TextField(null=True, verbose_name='\u6848\u4ef6\u6982\u8981', blank=True)),
                ('start_date', models.DateField(null=True, verbose_name='\u958b\u59cb\u65e5', blank=True)),
                ('end_date', models.DateField(null=True, verbose_name='\u7d42\u4e86\u65e5', blank=True)),
                ('address', models.CharField(max_length=255, null=True, verbose_name='\u4f5c\u696d\u5834\u6240', blank=True)),
                ('status', models.IntegerField(verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9', choices=[(1, '\u63d0\u6848'), (2, '\u4e88\u7b97\u5be9\u67fb'), (3, '\u4e88\u7b97\u78ba\u5b9a'), (4, '\u5b9f\u65bd\u4e2d'), (5, '\u5b8c\u4e86')])),
                ('boss', models.ForeignKey(related_name='boss_set', verbose_name='\u6848\u4ef6\u8cac\u4efb\u8005', blank=True, to='eb.ClientMember', null=True)),
                ('client', models.ForeignKey(verbose_name='\u4f1a\u793e', blank=True, to='eb.Client', null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u6848\u4ef6',
                'verbose_name_plural': '\u6848\u4ef6',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u6d3b\u52d5\u540d\u79f0')),
                ('open_date', models.DateTimeField(default=datetime.datetime(2015, 9, 12, 16, 48, 26, 614021), verbose_name='\u958b\u50ac\u65e5\u6642')),
                ('address', models.CharField(max_length=255, verbose_name='\u6d3b\u52d5\u5834\u6240')),
                ('content', models.TextField(verbose_name='\u6d3b\u52d5\u5185\u5bb9')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('client_members', models.ManyToManyField(to='eb.ClientMember', null=True, verbose_name='\u53c2\u52a0\u3057\u3066\u3044\u308b\u304a\u5ba2\u69d8', blank=True)),
                ('members', models.ManyToManyField(to='eb.Member', null=True, verbose_name='\u53c2\u52a0\u3057\u3066\u3044\u308b\u793e\u54e1', blank=True)),
                ('project', models.ForeignKey(verbose_name='\u6848\u4ef6', to='eb.Project')),
            ],
            options={
                'ordering': ['project', 'open_date'],
                'verbose_name': '\u6848\u4ef6\u6d3b\u52d5',
                'verbose_name_plural': '\u6848\u4ef6\u6d3b\u52d5',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('start_date', models.DateField(null=True, verbose_name='\u958b\u59cb\u65e5', blank=True)),
                ('end_date', models.DateField(null=True, verbose_name='\u7d42\u4e86\u65e5', blank=True)),
                ('price', models.IntegerField(default=0, verbose_name='\u5358\u4fa1')),
                ('status', models.IntegerField(default=1, verbose_name='\u30b9\u30c6\u30fc\u30bf\u30b9', choices=[(1, '\u63d0\u6848\u4e2d'), (2, '\u4f5c\u696d\u4e2d'), (3, '\u4f5c\u696d\u7d42\u4e86')])),
                ('member', models.ForeignKey(verbose_name='\u540d\u524d', to='eb.Member')),
                ('project', models.ForeignKey(verbose_name='\u6848\u4ef6\u540d\u79f0', to='eb.Project')),
            ],
            options={
                'verbose_name': '\u6848\u4ef6\u30e1\u30f3\u30d0\u30fc',
                'verbose_name_plural': '\u6848\u4ef6\u30e1\u30f3\u30d0\u30fc',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='\u7d4c\u9a13\u5e74\u6570', choices=[(0, '\u672a\u7d4c\u9a13\u8005\u53ef'), (1, '\uff11\u5e74\u4ee5\u4e0a'), (2, '\uff12\u5e74\u4ee5\u4e0a'), (3, '\uff13\u5e74\u4ee5\u4e0a'), (5, '\uff15\u5e74\u4ee5\u4e0a'), (10, '\uff11\uff10\u5e74\u4ee5\u4e0a')])),
                ('description', models.TextField(null=True, verbose_name='\u5099\u8003', blank=True)),
                ('project', models.ForeignKey(verbose_name='\u6848\u4ef6', to='eb.Project')),
            ],
            options={
                'verbose_name': '\u6848\u4ef6\u306e\u30b9\u30ad\u30eb\u8981\u6c42',
                'verbose_name_plural': '\u6848\u4ef6\u306e\u30b9\u30ad\u30eb\u8981\u6c42',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('employee_id', models.CharField(unique=True, max_length=30, verbose_name='\u793e\u54e1ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u524d')),
                ('email', models.EmailField(max_length=75, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('company', models.ForeignKey(verbose_name='\u4f1a\u793e', to='eb.Company')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u55b6\u696d\u54e1',
                'verbose_name_plural': '\u55b6\u696d\u54e1',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u90e8\u7f72\u540d')),
                ('company', models.ForeignKey(verbose_name='\u4f1a\u793e', to='eb.Company')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u90e8\u7f72',
                'verbose_name_plural': '\u90e8\u7f72',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u79f0')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u30b9\u30ad\u30eb',
                'verbose_name_plural': '\u30b9\u30ad\u30eb',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=30, verbose_name='\u4f1a\u793e\u540d')),
                ('japanese_spell', models.CharField(max_length=30, null=True, verbose_name='\u30d5\u30ea\u30ab\u30ca', blank=True)),
                ('found_date', models.DateField(null=True, verbose_name='\u8a2d\u7acb\u5e74\u6708\u65e5', blank=True)),
                ('capital', models.BigIntegerField(null=True, verbose_name='\u8cc7\u672c\u91d1', blank=True)),
                ('post_code', models.CharField(max_length=8, null=True, verbose_name='\u90f5\u4fbf\u756a\u53f7', blank=True)),
                ('address1', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff11', blank=True)),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='\u4f4f\u6240\uff12', blank=True)),
                ('tel', models.CharField(max_length=15, null=True, verbose_name='\u96fb\u8a71\u756a\u53f7', blank=True)),
                ('fax', models.CharField(max_length=15, null=True, verbose_name='\u30d5\u30a1\u30c3\u30af\u30b9', blank=True)),
                ('president', models.CharField(max_length=30, null=True, verbose_name='\u4ee3\u8868\u8005\u540d', blank=True)),
                ('employee_count', models.IntegerField(null=True, verbose_name='\u5f93\u696d\u54e1\u6570', blank=True)),
                ('sale_amount', models.BigIntegerField(null=True, verbose_name='\u58f2\u4e0a\u9ad8', blank=True)),
                ('payment_type', models.CharField(max_length=2, null=True, verbose_name='\u652f\u6255\u65b9\u6cd5', blank=True)),
                ('payment_day', models.CharField(max_length=2, null=True, verbose_name='\u652f\u6255\u65e5', blank=True)),
                ('comment', models.TextField(null=True, verbose_name='\u5099\u8003', blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2015, 9, 12, 16, 48, 26, 608631), auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2015, 9, 12, 16, 48, 26, 608656), auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u5354\u529b\u4f1a\u793e',
                'verbose_name_plural': '\u5354\u529b\u4f1a\u793e',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='section',
            field=models.ForeignKey(verbose_name='\u90e8\u7f72', to='eb.Section'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectskill',
            name='skill',
            field=models.ForeignKey(verbose_name='\u30b9\u30ad\u30eb', to='eb.Skill'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='salesperson',
            field=models.ManyToManyField(to='eb.Salesperson', null=True, verbose_name='\u53c2\u52a0\u3057\u3066\u3044\u308b\u55b6\u696d\u54e1', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='eb.Member', null=True, through='eb.ProjectMember', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='middleman',
            field=models.ForeignKey(related_name='middleman_set', verbose_name='\u6848\u4ef6\u9023\u7d61\u8005', blank=True, to='eb.ClientMember', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='salesperson',
            field=models.ForeignKey(verbose_name='\u55b6\u696d\u54e1', blank=True, to='eb.Salesperson', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='eb.Skill', null=True, verbose_name='\u30b9\u30ad\u30eb\u8981\u6c42', through='eb.ProjectSkill', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='member',
            name='salesperson',
            field=models.ForeignKey(verbose_name='\u55b6\u696d\u54e1', blank=True, to='eb.Salesperson', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='member',
            name='section',
            field=models.ForeignKey(verbose_name='\u90e8\u7f72', to='eb.Section'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(null=True, blank=True, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
